sudo ovs-ofctl -O OpenFlow14 del-flows s1
sudo ovs-ofctl -O OpenFlow14 del-flows s2
sudo ovs-ofctl -O OpenFlow14 del-flows s3
sudo ovs-ofctl -O OpenFlow14 del-flows s4
sudo ovs-ofctl -O OpenFlow14 del-flows s5
sudo ovs-ofctl -O OpenFlow14 del-flows s6
sudo ovs-ofctl -O OpenFlow14 del-flows s7
sudo ovs-ofctl -O OpenFlow14 del-flows s8
sudo ovs-ofctl -O OpenFlow14 del-flows s9